services:
  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - app
    ports:
      - 80:80

  app:
    build: ./app
    container_name: app
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    ## 永続化が必要な場合は有効にする
    # volumes:
    # - ./mongo/init.js:/workmng_db/init.js:ro # mongoの専用ユーザを作成する場合
    # - ./mongo/mongo-data:/data/db
    ## 認証機能を使用する場合
    # environment:
    #   MONGO_INITDB_DATABASE: admin
    # command: [ mongod, --auth ]
    command: [ mongod ]
