services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./html:/var/www/html
      - /root/nginx/log:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt

  app:
    build: ./app
    container_name: app
    restart: always
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ## 永続化が必要な場合は有効にする
    volumes:
      # - ./mongo/init.js:/workmng_db/init.js:ro # mongoの専用ユーザを作成する場合
      - ./mongo/mongo-data:/data/db
    ## 認証機能を使用する場合
    # environment:
    #   MONGO_INITDB_DATABASE: admin
    # command: [ mongod, --auth ]
    command: [ mongod ]
